### ISSUE TITLE
Remove colours from inline css

### ISSUE THREAD

**Issue by badlydrawnrob** [badlydrawnrob/print-first-css#64]
> Currently styling `<code><strong>...` as red
> Currently styling `<code><em>...` as blue
>
> **These shouldn't be in Print First CSS**
> They should be in Anki themes

I feel for standard writing all `inline code` should be uniform. That could be red on grey background, white on a black background, I've even seen pink on a white background but that seems like overkill!

**Comment by Teja-11** [comment]
can i work on this?

**Comment by badlydrawnrob** [comment]
@Teja-11 I think it's [solved already](https://github.com/badlydrawnrob/print-first-css/commit/3d39dfec1809ae579915e49daee83e5a2688e792)! I forgot to close out the issue. Thanks for offering though 😉 — if you have any general ideas about css for writing, create a child theme (repo) and you can ping me any ideas from there. I'm trying to keep this repo as stripped back as possible.

**Comment by badlydrawnrob** [comment]
@Teja-11 I think it's [solved already](https://github.com/badlydrawnrob/print-first-css/commit/3d39dfec1809ae579915e49daee83e5a2688e792)! I forgot to close out the issue. Thanks for offering though 😉 — if you have any general ideas about css for writing, create a child theme (repo) and you can ping me any ideas from there. I'm trying to keep this repo as stripped back as possible.
